AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Layout/ElseAlignment:
  Enabled: False

Layout/EndAlignment:
  Enabled: False

Layout/IndentationWidth:
  Enabled: False
